defmodule AbuubaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :abuuba

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_abuuba_key",
    signing_salt: "FMGwtW1k",
    same_site: "Lax"
  ]

  # `peer_data` as well as the session, because the sign-up form is a LiveView
  # and the address-based sign-up blocks are worth nothing if the one form a
  # stranger can reach cannot see which address they came from. See
  # `AbuubaWeb.ClientIP`.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :abuuba,
    gzip: not code_reloading?,
    only: AbuubaWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Uploads, served from wherever they were stored rather than from the
  # application's own static directory: what somebody uploads is not part of
  # the build, and a release that shipped its users' pictures inside it could
  # not be redeployed without them.
  #
  # `Plug.Static` resolves the path itself and refuses anything that climbs out
  # of `from`, which is the check that matters here: the name in the URL is a
  # stranger's to write.
  plug Plug.Static,
    at: "/media",
    from: {Abuuba.Media.Storage.Local, :root, []},
    gzip: false,
    # Named after an id that is never reused, so a cached copy can never be the
    # wrong picture.
    cache_control_for_etags: "public, max-age=31536000, immutable",
    # Everything under here was uploaded by a stranger, and it is served from
    # this server's own origin — which is where the session cookie lives.
    #
    # The stored type comes from what the upload claimed, so a file whose bytes
    # are HTML can be stored as `image/png`. `nosniff` is what stops a browser
    # looking past that declaration and rendering it, and the policy is the
    # second line: even served as HTML it may not load a script, reach the
    # network, or be framed.
    headers: %{
      "x-content-type-options" => "nosniff",
      "content-security-policy" => "default-src 'none'; sandbox",
      "cross-origin-resource-policy" => "cross-origin"
    }

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :abuuba
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    # Keeps the raw body for the inbox paths: an HTTP signature covers the
    # bytes that arrived, and a re-encoding of the parsed JSON is not those
    # bytes. See AbuubaWeb.Plugs.CacheBodyReader.
    body_reader: {AbuubaWeb.Plugs.CacheBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  # Ahead of the router, because a pipeline only runs once a route has matched
  # and a browser client has to be able to read a 404 too. See the plug for why
  # the API is open to any origin.
  plug AbuubaWeb.Plugs.APIHeaders

  # Before the router, because it rewrites the path the router matches on. A
  # pipeline runs only once a route has already matched, which is too late.
  plug AbuubaWeb.Plugs.FeedSuffix
  plug AbuubaWeb.Router
end
