defmodule Abuuba.Importer.CLITest do
  # Not async: it moves environment variables and the registered steps, and
  # both are global.
  use Abuuba.DataCase, async: false

  alias Abuuba.Importer.Checkpoint
  alias Abuuba.Importer.CLI
  alias Abuuba.Importer.SourceRepo
  alias Abuuba.ImportSteps

  describe "a release can run it" do
    test "nothing on the command's path calls Mix" do
      # `mix abuuba.import` does not exist on a server: the image ships a
      # release and a release has no Mix. So the command itself has to be free
      # of it, and a `Mix.shell().info/1` added here later would fail nowhere
      # except on somebody's takeover.
      #
      # Calibrated against the task, which does call Mix — a check that reads
      # "no Mix anywhere" because it is looking in the wrong place would pass
      # for the wrong reason.
      assert Mix in called_modules(Mix.Tasks.Abuuba.Import)

      refute Mix in called_modules(CLI)
      refute Mix in called_modules(Abuuba.Release)
    end

    test "and both front ends parse the same options" do
      # The task rejects anything not in this list, so a flag added to the
      # command and not to it is live on a release and unknown in a checkout.
      assert Keyword.keys(CLI.switches()) == [:execute, :reset, :verify, :media_root]
    end
  end

  describe "the application an import starts" do
    test "keeps everything it is not deliberately turning off" do
      # Merged onto the deployed configuration, never replacing it. Oban
      # without its `:repo` cannot start, and a container that dies in its
      # supervision tree says nothing about the import at all.
      config = CLI.startup_config()

      assert config[Oban][:repo] == Abuuba.Repo
      assert config[Oban][:queues] == false
      assert config[Oban][:plugins] == false
      refute config[AbuubaWeb.Endpoint][:server]
      assert config[AbuubaWeb.Endpoint][:url]
    end
  end

  describe "before anything can run" do
    test "it says which variable is missing rather than failing to connect" do
      with_env(%{"MASTODON_DATABASE_URL" => nil})

      assert {:error, message} = CLI.run()
      assert message =~ "MASTODON_DATABASE_URL"
    end

    test "and the release entry point says the same thing" do
      with_env(%{"MASTODON_DATABASE_URL" => nil})

      assert_raise RuntimeError, ~r/MASTODON_DATABASE_URL/, fn ->
        Abuuba.Release.import_mastodon()
      end
    end
  end

  describe "verifying" do
    setup do
      with_env(%{"MASTODON_DATABASE_URL" => source_url()})
      on_exit(&stop_source/0)

      :ok
    end

    test "reports what every step checked" do
      with_steps([ImportSteps.Stub])

      assert {:ok, output} = CLI.run(verify: true)
      assert output =~ "stub: 1 checked, 0 that do not match"
      assert output =~ "all good"
    end

    test "and answers with an error when a step does not check out" do
      with_steps([ImportSteps.Failing])

      assert {:error, output} = CLI.run(verify: true)
      assert output =~ "1 that do not match"
      assert output =~ "Nothing above is a warning"
    end

    test "opens the source once, so a second command in the same node is not a crash" do
      # `bin/abuuba eval` is a fresh node every time, but a dry run followed by
      # an --execute in one IEx session is not, and `already_started` is not a
      # failure to hand an admin.
      with_steps([ImportSteps.Stub])

      assert {:ok, _pid} = SourceRepo.connect(source_url())
      assert {:ok, output} = CLI.run(verify: true)
      assert output =~ "stub"
    end
  end

  describe "a dry run that cannot start" do
    test "reports the problems, and that nothing was written" do
      # Pointed at a database that is reachable and is not a Mastodon instance,
      # so the checks answer rather than the connection. What is being pinned
      # is the report: an admin who is refused has to be told why, and told
      # that the refusal happened before anything was written.
      with_env(%{"MASTODON_DATABASE_URL" => source_url()})
      on_exit(&stop_source/0)

      assert {:error, output} = CLI.run()
      assert output =~ "The import cannot start yet"
      assert output =~ "schema_version"
      assert output =~ "Nothing has been written"
    end
  end

  describe "starting over" do
    test "--reset clears the checkpoints and says so" do
      Checkpoint.record("stub_step", 42, 1)
      with_env(%{"MASTODON_DATABASE_URL" => nil})

      assert {:error, output} = CLI.run(reset: true)
      assert output =~ "Checkpoints cleared"
      assert Checkpoint.all() == []
    end
  end

  # The external functions a module's compiled code can call. `:beam_lib` reads
  # the import table rather than the source, so a call made through an alias or
  # generated by a macro is counted too.
  defp called_modules(module) do
    {:ok, {^module, [imports: imports]}} = :beam_lib.chunks(:code.which(module), [:imports])

    imports |> Enum.map(fn {called, _fun, _arity} -> called end) |> Enum.uniq()
  end

  defp source_url do
    config = Repo.config()

    "ecto://#{config[:username]}:#{config[:password]}@#{config[:hostname]}/#{config[:database]}"
  end

  # Teardown, written to survive whichever way the pool is already on its way
  # down: an Ecto repo's supervisor stops with `:shutdown` rather than
  # `:normal`, and `Supervisor.stop/1` calls that an error.
  defp stop_source do
    if pid = Process.whereis(SourceRepo) do
      try do
        Supervisor.stop(pid)
      catch
        :exit, _reason -> :ok
      end
    end
  end
end
