defmodule Abuuba.Bench.Report do
  @moduledoc """
  The Markdown a run leaves behind.

  A benchmark result is a claim about somebody else's software, so the report
  has to carry enough for a reader to disagree with it: which versions ran,
  on what machine, against what data, and what was measured how. A table of
  numbers with none of that is marketing.

  ## Nothing is summarised into a single figure

  There is no "abuuba is N times faster". Each measurement stands on its own,
  with both sides next to each other and the ratio spelled out, because the
  ratios differ and a reader who cares about timeline reads is not helped by
  an average that includes fan-out.

  ## A measurement that did not run says so

  A missing number is written as such rather than left out of the table.
  Silence in a comparison reads as "no difference", and the reason it is
  missing is usually the interesting part.
  """

  alias Abuuba.Bench.Dataset

  @doc """
  Renders a run.

  `measurements` is a list of maps with `:name`, `:unit`, `:abuuba` and
  `:mastodon`, any of which may be `nil` where that side did not produce a
  number.
  """
  @spec render(map()) :: String.t()
  def render(run) do
    """
    # abuuba vs Mastodon

    #{generated_at(run)}

    ## What ran

    #{versions(run)}

    ## On what machine

    #{machine(run)}

    ## Against what data

    #{Dataset.describe(run[:profile] || :small)}

    Both servers were seeded from the same description, in the same order, and
    given a warm-up pass before anything was measured.

    ## Results
    #{warnings(run[:warnings] || [])}
    #{table(run[:measurements] || [])}

    #{resolution(run[:measurements] || [])}
    #{footnotes(run[:measurements] || [])}
    ## How to disagree with this

    Run it yourself: `mix abuuba.bench` needs Docker and nothing else. The
    methodology, including what is deliberately left at its defaults on both
    sides, is in `bench/README.md`.
    """
  end

  ## Sections

  defp generated_at(run) do
    case run[:generated_at] do
      %DateTime{} = at -> "Generated #{DateTime.to_iso8601(at)}."
      _unknown -> "Generated by `mix abuuba.bench`."
    end
  end

  defp versions(run) do
    """
    | | Version |
    | --- | --- |
    | abuuba | #{value(run[:abuuba_version])} |
    | Mastodon | #{value(run[:mastodon_version])} |
    | Postgres | #{value(run[:postgres_version])} |
    """
  end

  defp machine(run) do
    """
    | | |
    | --- | --- |
    | CPU | #{value(run[:cpu])} |
    | Cores | #{value(run[:cores])} |
    | Memory | #{value(run[:memory])} |
    | Kernel | #{value(run[:kernel])} |
    | Docker | #{value(run[:docker])} |
    """
  end

  defp table([]) do
    "Nothing was measured. A run that produced no numbers is a run that failed."
  end

  defp table(measurements) do
    rows = Enum.map_join(measurements, "\n", &row/1)

    """
    | Measurement | abuuba | Mastodon | abuuba ÷ Mastodon |
    | --- | ---: | ---: | ---: |
    #{rows}
    """
  end

  defp row(%{name: name} = measurement) do
    unit = measurement[:unit] || ""

    abuuba = cell(measurement[:abuuba], measurement[:abuuba_range], unit)
    mastodon = cell(measurement[:mastodon], measurement[:mastodon_range], unit)

    "| #{name} | #{abuuba} | #{mastodon} | #{ratio(measurement)} |"
  end

  # A figure sampled over a window carries the range of the samples behind it.
  # The median alone hides how much they disagreed, and that disagreement is
  # the reader's warning that the stack was doing something other than what the
  # label says: an idle CPU median of 3.9% drawn from samples running 0.6% to
  # 86.8% is a number, but it is not an answer, and printing it bare invites a
  # reader to quote it. A gauge read once has no spread and gets none.
  defp cell(value, {low, high}, unit) when is_number(low) and is_number(high) do
    "#{number(value, unit)} (#{plain(low)}–#{plain(high)})"
  end

  defp cell(value, _no_range, unit), do: number(value, unit)

  defp plain(value) when is_float(value), do: to_string(Float.round(value, 2))
  defp plain(value), do: to_string(value)

  # Lower is better for a time and higher for a rate, and the report does not
  # guess which: the ratio is stated as "abuuba : Mastodon" and the unit says
  # which direction is good.
  defp ratio(%{abuuba: abuuba, mastodon: mastodon})
       when is_number(abuuba) and is_number(mastodon) and mastodon != 0 do
    "#{Float.round(abuuba / mastodon, 2)}×"
  end

  defp ratio(_incomparable), do: "—"

  defp number(nil, _unit), do: "not measured"

  defp number(value, unit) when is_float(value), do: "#{Float.round(value, 2)} #{unit}"
  defp number(value, unit), do: "#{value} #{unit}"

  # Named rather than counted, because "one measurement did not run" is not
  # something a reader can act on.
  # A run measured on top of a queue that never drained is still a result, and
  # the harness says so on the console. It used to say it only there: the
  # warning went to warnings.txt, the renderer never read that file, and the
  # report came out looking exactly like a clean one. A caveat the reader
  # cannot see is not a caveat.
  defp warnings([]), do: ""

  defp warnings(lines) do
    "\n> **This run is not clean.** " <>
      Enum.map_join(lines, " ", &String.trim/1) <>
      " Numbers below were measured on top of that backlog and understate the\n" <>
      "> side that was still busy.\n"
  end

  # How well each side of the fan-out row was actually resolved. The prober
  # polls, so a side that finished in three polls carries a poll-cycle of
  # uncertainty and a side that took two hundred carries almost none. Printing
  # 755.9 and 57167.7 side by side gives them equal apparent authority when one
  # is worth a third of itself and the other half a percent.
  defp resolution(measurements) do
    case Enum.find(measurements, &Map.has_key?(&1, :polls)) do
      %{polls: {a, m}} when is_integer(a) and is_integer(m) ->
        """

        Fan-out was polled #{a} times on the abuuba side and #{m} on Mastodon's.
        One poll cycle is the uncertainty on each: the fewer the polls, the
        coarser that side of the row.
        """

      _ ->
        ""
    end
  end

  defp footnotes(measurements) do
    missing =
      Enum.filter(measurements, &(is_nil(&1[:abuuba]) or is_nil(&1[:mastodon])))

    if missing == [] do
      ""
    else
      lines =
        Enum.map_join(missing, "\n", &"- #{&1.name}: #{&1[:note] || "did not produce a number"}")

      """
      ### Not measured

      #{lines}

      """
    end
  end

  defp value(nil), do: "unknown"
  defp value(value), do: to_string(value)
end
