import Config

# Configure your database
config :abuuba, Abuuba.Repo,
  username: System.get_env("PGUSER") || "postgres",
  password: System.get_env("PGPASSWORD") || "postgres",
  hostname: "localhost",
  database: "abuuba_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :abuuba, AbuubaWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "wpF/+4Nh2XYwuzxcVasJVMFcdJHGAPdv9MMS2sm7yTC1lEig8O23tGu+TKWB5DfL",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:abuuba, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:abuuba, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :abuuba, dev_routes: true

# The first account registered on a fresh database can reach the admin area.
# Here only: on a public server this would mean whoever signs up first owns it.
config :abuuba, first_user_is_admin: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# A fixed, deliberately public key: dev data is throwaway and a developer
# should never have to set an environment variable to run the suite. Production
# reads its key from the environment, see config/runtime.exs.
config :abuuba, Abuuba.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvA0yXCETFg0=")}
  ]

# The host this server calls itself in every URI it hands to other servers.
# Never taken from the request: a request arriving on another hostname would
# otherwise make us claim actors under it.
config :abuuba, local_domain: "localhost:4000", local_scheme: "http"
