defmodule Abuuba.Search.TSVector do
  @moduledoc """
  Postgres' `tsvector`, as far as Ecto needs to know about it.

  Never read and never written: the column is generated by the database and is
  only ever named in a `where`. The type exists so the schema can mention the
  field at all, which is what lets a query refer to it by name instead of
  reaching for a raw fragment with a table alias in it.
  """

  use Ecto.Type

  @impl Ecto.Type
  def type, do: :tsvector

  @impl Ecto.Type
  def cast(_value), do: :error

  @impl Ecto.Type
  def load(value), do: {:ok, value}

  @impl Ecto.Type
  def dump(_value), do: :error
end
